enhavo_app:
    menu:
        dashboard:
            type: dashboard
        user:
            type: user
        page:
            type: page
        navigation:
            type: navigation

enhavo_block:
    blocks:
        picture:
            type: picture
        text:
            type: text
        text_picture:
            type: text_picture
        blockquote:
            type: blockquote
        video:
            type: video
        one_column:
            type: one_column
        two_column:
            type: two_column
        three_column:
            type: three_column
