enhavo_app:
    menu:
        dashboard:
            type: dashboard
        user:
            type: user
        page:
            type: page
        navigation:
            type: navigation

enhavo_block:
    blocks:
        dummy:
            type: base
            label: 'Dummy'
            factory: App\Factory\DummyBlockFactory
            model: App\Entity\DummyBlock
            form: App\Form\Type\DummyBlockType
            template: 'theme/block/dummy.html.twig'

        dummy_list:
            type: base
            label: 'Dummy-List'
            factory: App\Factory\DummyListBlockFactory
            model: App\Entity\DummyListBlock
            form: App\Form\Type\DummyListBlockType
            template: 'theme/block/dummy-list.html.twig'
